apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}-service
  labels:
    app: {{ .Values.labels.app }}-app
    env: {{ .Values.labels.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
  ports:
    - port: {{ .Values.port }}
      nodePort: 30009
      protocol: TCP
